---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fastapi-demo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/fastapi
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-demo
  targetNamespace: default
